spring.application.name=marketplace

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA_NAME:public}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.default-schema=${DB_SCHEMA_NAME:public}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

logging.level.root=INFO
logging.level.com.grapefruitapps=DEBUG
logging.level.liquibase = INFO

jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration=86400000
